'use strict';

const { colors: C } = require('./color-definitions.cjs');

// Source theme object that references base colors via C.* aliases.
module.exports = {
  "name": "Hate of Nature 2",
  "type": "dark",
  "colors": {
    "quickInput.background": C.HEX_0D1303,
    "quickInput.foreground": C.HEX_92B161,
    "quickInputList.focusBackground": C.HEX_172304,
    "quickInputList.focusForeground": C.HEX_92B161,
    "quickInputList.focusIconForeground": C.HEX_F92672,
    "editorGroupHeader.tabsBackground": C.HEX_1A2D00,
    "editorGroupHeader.tabsBorder": C.HEX_1A2D00,
    "tab.activeBackground": C.HEX_1A2D00,
    "tab.activeForeground": C.HEX_92B161,
    "tab.inactiveBackground": C.HEX_172304,
    "tab.inactiveForeground": C.HEX_57702F,
    "tab.hoverBackground": C.HEX_2E4012,
    "tab.hoverForeground": C.HEX_92B161,
    "tab.border": C.HEX_172304,
    "tab.activeBorder": C.HEX_92B161,
    "tab.unfocusedActiveBorder": C.HEX_61704A,
    "tab.dragAndDropBorder": C.HEX_92B161,
    "menubar.background": C.HEX_172304,
    "menubar.foreground": C.HEX_92B161,
    "menu.background": C.HEX_172304,
    "menu.foreground": C.HEX_92B161,
    "menu.selectionBackground": C.HEX_3A5412,
    "menu.selectionForeground": C.HEX_92B161,
    "menu.separatorBackground": C.HEX_2E4012,
    "editor.background": C.HEX_1A2D00,
    "editor.foreground": C.HEX_92B161,
    "editorLineNumber.foreground": C.HEX_61704A,
    "editorLineNumber.activeForeground": C.HEX_61704A,
    "editor.selectionBackground": C.HEX_3A6BFF40,
    "editor.selectionHighlightBackground": C.HEX_3A6BFF20,
    "editor.inactiveSelectionBackground": C.HEX_2E4012,
    "editor.lineHighlightBackground": C.HEX_92B16150,
    "editor.lineHighlightBorder": C.HEX_92B16100,
    "editorCursor.foreground": C.HEX_92B161,
    "editorCursor.background": C.HEX_92B161,
    "editorMultiCursor.primary.foreground": C.HEX_92B161,
    "editorMultiCursor.primary.background": C.HEX_92B161,
    "editorMultiCursor.secondary.foreground": C.HEX_61704A,
    "editorMultiCursor.secondary.background": C.HEX_61704A,
    "editor.placeholder.foreground": C.HEX_61704A,
    "editor.compositionBorder": C.HEX_92B161,
    "editor.selectionForeground": C.HEX_FFFFFF,
    "editor.selectionHighlightBorder": C.HEX_92B161,
    "editor.wordHighlightTextBorder": C.HEX_92B161,
    "editor.findMatchForeground": C.HEX_FFFFFF,
    "editor.findMatchHighlightForeground": C.HEX_92B161,
    "editor.findRangeHighlightBorder": C.HEX_819AFF,
    "editor.findMatchBorder": C.HEX_F92672,
    "editor.findMatchHighlightBorder": C.HEX_E6DB74,
    "search.resultsInfoForeground": C.HEX_92B161,
    "searchEditor.findMatchBackground": C.HEX_3A5412,
    "searchEditor.findMatchBorder": C.HEX_F92672,
    "searchEditor.textInputBorder": C.HEX_1A2D00,
    "editor.hoverHighlightBackground": C.HEX_2E4012,
    "editorWatermark.foreground": C.HEX_61704A,
    "editorUnicodeHighlight.border": C.HEX_F92672,
    "editorUnicodeHighlight.background": C.HEX_2E4012,
    "editorLink.activeForeground": C.HEX_F92672,
    "editor.rangeHighlightBorder": C.HEX_819AFF,
    "editor.symbolHighlightBorder": C.HEX_66D9EF,
    "editorIndentGuide.background1": C.HEX_2E4012,
    "editorIndentGuide.background2": C.HEX_2E4012,
    "editorIndentGuide.background3": C.HEX_2E4012,
    "editorIndentGuide.background4": C.HEX_2E4012,
    "editorIndentGuide.background5": C.HEX_2E4012,
    "editorIndentGuide.background6": C.HEX_2E4012,
    "editorIndentGuide.activeBackground1": C.HEX_3A5412,
    "editorIndentGuide.activeBackground2": C.HEX_3A5412,
    "editorIndentGuide.activeBackground3": C.HEX_3A5412,
    "editorIndentGuide.activeBackground4": C.HEX_3A5412,
    "editorIndentGuide.activeBackground5": C.HEX_3A5412,
    "editorIndentGuide.activeBackground6": C.HEX_3A5412,
    "editorInlayHint.background": C.HEX_172304,
    "editorInlayHint.foreground": C.HEX_92B161,
    "editorInlayHint.typeForeground": C.HEX_A6E22E,
    "editorInlayHint.typeBackground": C.HEX_2E4012,
    "editorInlayHint.parameterForeground": C.HEX_FD971F,
    "editorInlayHint.parameterBackground": C.HEX_2E4012,
    "editorRuler.foreground": C.HEX_414339,
    "editor.linkedEditingBackground": C.HEX_2E4012,
    "editorCodeLens.foreground": C.HEX_61704A,
    "editorLightBulb.foreground": C.HEX_E6DB74,
    "editorLightBulbAutoFix.foreground": C.HEX_A6E22E,
    "editorLightBulbAi.foreground": C.HEX_66D9EF_2,
    "editorBracketMatch.background": C.HEX_2E4012,
    "editorBracketMatch.border": C.HEX_92B161,
    "editorBracketHighlight.foreground1": C.HEX_F92672,
    "editorBracketHighlight.foreground2": C.HEX_A6E22E,
    "editorBracketHighlight.foreground3": C.HEX_66D9EF,
    "editorBracketHighlight.foreground4": C.HEX_E6DB74,
    "editorBracketHighlight.foreground5": C.HEX_AE81FF,
    "editorBracketHighlight.foreground6": C.HEX_FD971F,
    "editorBracketHighlight.unexpectedBracket.foreground": C.HEX_F92672,
    "editorBracketPairGuide.activeBackground1": C.HEX_F92672,
    "editorBracketPairGuide.activeBackground2": C.HEX_A6E22E,
    "editorBracketPairGuide.activeBackground3": C.HEX_66D9EF,
    "editorBracketPairGuide.activeBackground4": C.HEX_E6DB74,
    "editorBracketPairGuide.activeBackground5": C.HEX_AE81FF,
    "editorBracketPairGuide.activeBackground6": C.HEX_FD971F,
    "editorBracketPairGuide.background1": C.HEX_2E4012,
    "editorBracketPairGuide.background2": C.HEX_2E4012,
    "editorBracketPairGuide.background3": C.HEX_2E4012,
    "editorBracketPairGuide.background4": C.HEX_2E4012,
    "editorBracketPairGuide.background5": C.HEX_2E4012,
    "editorBracketPairGuide.background6": C.HEX_2E4012,
    "editor.foldBackground": C.HEX_2E4012,
    "editor.foldPlaceholderForeground": C.HEX_61704A,
    "editorOverviewRuler.background": C.HEX_0D1303,
    "editorOverviewRuler.border": C.HEX_1A2D00,
    "editorOverviewRuler.findMatchForeground": C.HEX_F92672,
    "editorOverviewRuler.rangeHighlightForeground": C.HEX_819AFF,
    "editorOverviewRuler.selectionHighlightForeground": C.HEX_3A5412,
    "editorOverviewRuler.wordHighlightForeground": C.HEX_4A6B1A,
    "editorOverviewRuler.wordHighlightStrongForeground": C.HEX_5A8A22,
    "editorOverviewRuler.wordHighlightTextForeground": C.HEX_4A6B1A,
    "editorOverviewRuler.modifiedForeground": C.HEX_E6DB74,
    "editorOverviewRuler.addedForeground": C.HEX_A6E22E,
    "editorOverviewRuler.deletedForeground": C.HEX_F92672,
    "editorOverviewRuler.errorForeground": C.HEX_F92672,
    "editorOverviewRuler.warningForeground": C.HEX_E6DB74,
    "editorOverviewRuler.infoForeground": C.HEX_819AFF,
    "editorOverviewRuler.bracketMatchForeground": C.HEX_92B161,
    "editorOverviewRuler.inlineChatInserted": C.HEX_66D9EF_2,
    "editorOverviewRuler.inlineChatRemoved": C.HEX_F92672,
    "editorError.foreground": C.HEX_F92672,
    "editorError.border": C.HEX_F92672,
    "editorError.background": C.HEX_2E4012,
    "editorWarning.foreground": C.HEX_E6DB74,
    "editorWarning.border": C.HEX_E6DB74,
    "editorWarning.background": C.HEX_2E4012,
    "editorInfo.foreground": C.HEX_819AFF,
    "editorInfo.border": C.HEX_819AFF,
    "editorInfo.background": C.HEX_2E4012,
    "editorHint.foreground": C.HEX_66D9EF_2,
    "editorHint.border": C.HEX_66D9EF_2,
    "problemsErrorIcon.foreground": C.HEX_F92672,
    "problemsWarningIcon.foreground": C.HEX_E6DB74,
    "problemsInfoIcon.foreground": C.HEX_819AFF,
    "editorUnnecessaryCode.border": C.HEX_61704A,
    "editorUnnecessaryCode.opacity": C.HEX_000000C0,
    "editorGutter.background": C.HEX_1A2D00_2,
    "editorGutter.modifiedBackground": C.HEX_E6DB74,
    "editorGutter.modifiedSecondaryBackground": C.HEX_2E4012,
    "editorGutter.addedBackground": C.HEX_A6E22E,
    "editorGutter.addedSecondaryBackground": C.HEX_2E4012,
    "editorGutter.deletedBackground": C.HEX_F92672,
    "editorGutter.deletedSecondaryBackground": C.HEX_2E4012,
    "editorGutter.commentRangeForeground": C.HEX_57702F,
    "editorGutter.commentGlyphForeground": C.HEX_57702F,
    "editorGutter.commentUnresolvedGlyphForeground": C.HEX_F92672,
    "editorGutter.foldingControlForeground": C.HEX_92B161,
    "editorGutter.itemGlyphForeground": C.HEX_92B161,
    "editorGutter.itemBackground": C.HEX_172304,
    "editorCommentsWidget.resolvedBorder": C.HEX_57702F,
    "editorCommentsWidget.unresolvedBorder": C.HEX_F92672,
    "editorCommentsWidget.rangeBackground": C.HEX_2E4012,
    "editorCommentsWidget.rangeActiveBackground": C.HEX_3A5412,
    "editorCommentsWidget.replyInputBackground": C.HEX_172304,
    "inlineEdit.gutterIndicator.primaryBorder": C.HEX_F92672,
    "inlineEdit.gutterIndicator.primaryForeground": C.HEX_FFFFFF,
    "inlineEdit.gutterIndicator.primaryBackground": C.HEX_F92672,
    "inlineEdit.gutterIndicator.secondaryBorder": C.HEX_E6DB74,
    "inlineEdit.gutterIndicator.secondaryForeground": C.HEX_172304,
    "inlineEdit.gutterIndicator.secondaryBackground": C.HEX_E6DB74,
    "inlineEdit.gutterIndicator.successfulBorder": C.HEX_A6E22E,
    "inlineEdit.gutterIndicator.successfulForeground": C.HEX_FFFFFF,
    "inlineEdit.gutterIndicator.successfulBackground": C.HEX_A6E22E,
    "inlineEdit.gutterIndicator.background": C.HEX_172304,
    "inlineEdit.originalBackground": C.HEX_2E4012,
    "inlineEdit.modifiedBackground": C.HEX_3A5412,
    "inlineEdit.originalChangedLineBackground": C.HEX_2E4012,
    "inlineEdit.originalChangedTextBackground": C.HEX_3A5412,
    "inlineEdit.modifiedChangedLineBackground": C.HEX_3A5412,
    "inlineEdit.modifiedChangedTextBackground": C.HEX_4A6B1A,
    "inlineEdit.originalBorder": C.HEX_61704A,
    "inlineEdit.modifiedBorder": C.HEX_92B161,
    "inlineEdit.tabWillAcceptModifiedBorder": C.HEX_A6E22E,
    "inlineEdit.tabWillAcceptOriginalBorder": C.HEX_A6E22E,
    "editorWhitespace.foreground": C.HEX_2E4012,
    "editorIndentGuide.background": C.HEX_2E4012,
    "editorIndentGuide.activeBackground": C.HEX_3A5412,
    "sideBar.background": C.HEX_172304,
    "sideBar.foreground": C.HEX_92B161,
    "sideBar.border": C.HEX_1A2D00,
    "sideBarTitle.foreground": C.HEX_92B161,
    "sideBarSectionHeader.background": C.HEX_1A2D00,
    "sideBarSectionHeader.foreground": C.HEX_92B161,
    "activityBar.background": C.HEX_1A2D00,
    "activityBar.foreground": C.HEX_92B161,
    "activityBar.inactiveForeground": C.HEX_57702F,
    "activityBar.border": C.HEX_172304,
    "activityBarBadge.background": C.HEX_F92672,
    "activityBarBadge.foreground": C.HEX_FFFFFF,
    "statusBar.background": C.HEX_172304,
    "statusBar.foreground": C.HEX_92B161,
    "statusBar.border": C.HEX_1A2D00,
    "statusBar.debuggingBackground": C.HEX_AE81FF,
    "statusBar.debuggingForeground": C.HEX_172304,
    "statusBar.noFolderBackground": C.HEX_172304,
    "statusBarItem.remoteBackground": C.HEX_F92672,
    "statusBarItem.remoteForeground": C.HEX_FFFFFF,
    "tab.activeBorderTop": C.HEX_92B161,
    "titleBar.activeBackground": C.HEX_172304,
    "titleBar.inactiveBackground": C.HEX_172304,
    "titleBar.activeForeground": C.HEX_92B161,
    "titleBar.inactiveForeground": C.HEX_57702F,
    "panel.background": C.HEX_172304,
    "panel.border": C.HEX_1A2D00,
    "panelTitle.activeBorder": C.HEX_92B161,
    "panelTitle.activeForeground": C.HEX_92B161,
    "panelTitle.inactiveForeground": C.HEX_57702F,
    "scrollbarSlider.background": C.HEX_3A5412,
    "scrollbarSlider.hoverBackground": C.HEX_4A6B1A,
    "scrollbarSlider.activeBackground": C.HEX_5A8A22,
    "button.background": C.HEX_3A5412,
    "button.foreground": C.HEX_92B161,
    "button.hoverBackground": C.HEX_4A6B1A,
    "dropdown.background": C.HEX_172304,
    "dropdown.border": C.HEX_1A2D00,
    "dropdown.foreground": C.HEX_92B161,
    "input.background": C.HEX_172304,
    "input.border": C.HEX_1A2D00,
    "input.foreground": C.HEX_92B161,
    "input.placeholderForeground": C.HEX_57702F,
    "list.activeSelectionBackground": C.HEX_3A5412,
    "list.activeSelectionForeground": C.HEX_92B161,
    "list.inactiveSelectionBackground": C.HEX_2E4012,
    "list.hoverBackground": C.HEX_2E4012,
    "list.focusBackground": C.HEX_2E4012,
    "list.highlightForeground": C.HEX_F92672,
    "terminal.background": C.HEX_0D1303,
    "terminal.foreground": C.HEX_92B161,
    "terminal.ansiBlack": C.HEX_0D1303,
    "terminal.ansiRed": C.HEX_C4265E,
    "terminal.ansiGreen": C.HEX_86B42B,
    "terminal.ansiYellow": C.HEX_B3B42B,
    "terminal.ansiBlue": C.HEX_6A7EC8,
    "terminal.ansiMagenta": C.HEX_8C6BC8,
    "terminal.ansiCyan": C.HEX_56ADBC,
    "terminal.ansiWhite": C.HEX_92B161,
    "terminal.ansiBrightBlack": C.HEX_172304,
    "terminal.ansiBrightRed": C.HEX_F92672_2,
    "terminal.ansiBrightGreen": C.HEX_A6E22E,
    "terminal.ansiBrightYellow": C.HEX_E2E22E,
    "terminal.ansiBrightBlue": C.HEX_819AFF,
    "terminal.ansiBrightMagenta": C.HEX_AE81FF,
    "terminal.ansiBrightCyan": C.HEX_66D9EF_2,
    "terminal.ansiBrightWhite": C.HEX_F8F8F2,
    "focusBorder": C.HEX_92B161,
    "foreground": C.HEX_92B161,
    "contrastBorder": C.HEX_1A2D00,
    "window.activeBorder": C.HEX_1A2D00,
    "window.inactiveBorder": C.HEX_172304,
    "textLink.foreground": C.HEX_F92672,
    "textLink.activeForeground": C.HEX_E6DB74,
    "textBlockQuote.background": C.HEX_2E4012,
    "textBlockQuote.border": C.HEX_61704A,
    "textCodeBlock.background": C.HEX_172304,
    "textPreformat.foreground": C.HEX_E6DB74,
    "textPreformat.background": C.HEX_172304,
    "textSeparator.foreground": C.HEX_2E4012,
    "toolbar.hoverBackground": C.HEX_2E4012,
    "toolbar.hoverOutline": C.HEX_92B161,
    "toolbar.activeBackground": C.HEX_3A5412,
    "editorActionList.background": C.HEX_172304,
    "editorActionList.foreground": C.HEX_92B161,
    "editorActionList.focusForeground": C.HEX_F92672,
    "editorActionList.focusBackground": C.HEX_2E4012,
    "button.border": C.HEX_61704A,
    "button.separator": C.HEX_2E4012,
    "button.secondaryForeground": C.HEX_92B161,
    "button.secondaryBackground": C.HEX_2E4012,
    "button.secondaryHoverBackground": C.HEX_3A5412,
    "checkbox.background": C.HEX_172304,
    "checkbox.foreground": C.HEX_92B161,
    "checkbox.disabled.background": C.HEX_172304,
    "checkbox.disabled.foreground": C.HEX_2E4012,
    "checkbox.border": C.HEX_61704A,
    "checkbox.selectBackground": C.HEX_3A5412,
    "checkbox.selectBorder": C.HEX_92B161,
    "radio.activeForeground": C.HEX_92B161,
    "radio.activeBackground": C.HEX_3A5412,
    "radio.activeBorder": C.HEX_92B161,
    "radio.inactiveForeground": C.HEX_61704A,
    "radio.inactiveBackground": C.HEX_172304,
    "radio.inactiveBorder": C.HEX_2E4012,
    "radio.inactiveHoverBackground": C.HEX_2E4012,
    "dropdown.listBackground": C.HEX_172304,
    "inputOption.activeBackground": C.HEX_3A5412,
    "inputOption.activeBorder": C.HEX_92B161,
    "inputOption.activeForeground": C.HEX_92B161,
    "inputOption.hoverBackground": C.HEX_2E4012,
    "inputValidation.errorBackground": C.HEX_F92672,
    "inputValidation.errorForeground": C.HEX_FFFFFF,
    "inputValidation.errorBorder": C.HEX_F92672,
    "inputValidation.infoBackground": C.HEX_819AFF,
    "inputValidation.infoForeground": C.HEX_172304,
    "inputValidation.infoBorder": C.HEX_819AFF,
    "inputValidation.warningBackground": C.HEX_E6DB74,
    "inputValidation.warningForeground": C.HEX_172304,
    "inputValidation.warningBorder": C.HEX_E6DB74,
    "scrollbar.shadow": C.HEX_172304,
    "badge.foreground": C.HEX_FFFFFF,
    "badge.background": C.HEX_F92672,
    "progressBar.background": C.HEX_92B161,
    "list.activeSelectionIconForeground": C.HEX_F92672,
    "list.dropBackground": C.HEX_3A5412,
    "list.focusForeground": C.HEX_92B161,
    "list.focusHighlightForeground": C.HEX_F92672,
    "list.focusOutline": C.HEX_92B161,
    "list.focusAndSelectionOutline": C.HEX_F92672,
    "list.inactiveSelectionForeground": C.HEX_92B161,
    "list.inactiveSelectionIconForeground": C.HEX_F92672,
    "list.inactiveFocusBackground": C.HEX_2E4012,
    "list.inactiveFocusOutline": C.HEX_92B161,
    "list.invalidItemForeground": C.HEX_F92672,
    "list.errorForeground": C.HEX_F92672,
    "list.warningForeground": C.HEX_E6DB74,
    "listFilterWidget.background": C.HEX_172304,
    "listFilterWidget.outline": C.HEX_92B161,
    "listFilterWidget.noMatchesOutline": C.HEX_F92672,
    "listFilterWidget.shadow": C.HEX_0D1303,
    "list.filterMatchBackground": C.HEX_3A5412,
    "list.filterMatchBorder": C.HEX_F92672,
    "list.deemphasizedForeground": C.HEX_61704A,
    "list.dropBetweenBackground": C.HEX_3A5412,
    "tree.indentGuidesStroke": C.HEX_2E4012,
    "tree.inactiveIndentGuidesStroke": C.HEX_2E4012,
    "tree.tableColumnsBorder": C.HEX_2E4012,
    "tree.tableOddRowsBackground": C.HEX_172304,
    "activityBar.dropBorder": C.HEX_92B161,
    "activityBar.activeBorder": C.HEX_92B161,
    "activityBar.activeBackground": C.HEX_2E4012,
    "activityBar.activeFocusBorder": C.HEX_F92672,
    "activityBarTop.foreground": C.HEX_92B161,
    "activityBarTop.activeBorder": C.HEX_F92672,
    "activityBarTop.inactiveForeground": C.HEX_61704A,
    "activityBarTop.dropBorder": C.HEX_92B161,
    "activityBarTop.background": C.HEX_172304,
    "activityBarTop.activeBackground": C.HEX_2E4012,
    "activityWarningBadge.foreground": C.HEX_FFFFFF,
    "activityWarningBadge.background": C.HEX_E6DB74,
    "activityErrorBadge.foreground": C.HEX_FFFFFF,
    "activityErrorBadge.background": C.HEX_F92672,
    "profileBadge.background": C.HEX_F92672,
    "profileBadge.foreground": C.HEX_FFFFFF,
    "profiles.sashBorder": C.HEX_1A2D00,
    "sideBar.dropBackground": C.HEX_3A5412,
    "sideBarSectionHeader.border": C.HEX_1A2D00,
    "sideBarActivityBarTop.border": C.HEX_1A2D00,
    "sideBarTitle.background": C.HEX_172304,
    "sideBarTitle.border": C.HEX_1A2D00,
    "sideBarStickyScroll.background": C.HEX_172304,
    "sideBarStickyScroll.border": C.HEX_1A2D00,
    "sideBarStickyScroll.shadow": C.HEX_0D1303,
    "minimap.findMatchHighlight": C.HEX_F92672,
    "minimap.selectionHighlight": C.HEX_3A5412,
    "minimap.errorHighlight": C.HEX_F92672,
    "minimap.warningHighlight": C.HEX_E6DB74,
    "minimap.background": C.HEX_0D1303,
    "minimap.selectionOccurrenceHighlight": C.HEX_4A6B1A,
    "minimap.foregroundOpacity": C.HEX_000000C0,
    "minimap.infoHighlight": C.HEX_819AFF,
    "minimap.chatEditHighlight": C.HEX_66D9EF_2,
    "minimapGutter.addedBackground": C.HEX_A6E22E,
    "minimapGutter.modifiedBackground": C.HEX_E6DB74,
    "minimapGutter.deletedBackground": C.HEX_F92672,
    "editorMinimap.inlineChatInserted": C.HEX_66D9EF_2,
    "editorGroup.border": C.HEX_1A2D00,
    "editorGroup.dropBackground": C.HEX_3A5412,
    "editorGroupHeader.noTabsBackground": C.HEX_0D1303,
    "editorGroupHeader.border": C.HEX_0D1303,
    "editorGroup.emptyBackground": C.HEX_0D1303,
    "editorGroup.focusedEmptyBorder": C.HEX_92B161,
    "editorGroup.dropIntoPromptForeground": C.HEX_92B161,
    "editorGroup.dropIntoPromptBackground": C.HEX_172304,
    "editorGroup.dropIntoPromptBorder": C.HEX_92B161,
    "tab.unfocusedActiveBackground": C.HEX_172304,
    "tab.unfocusedActiveForeground": C.HEX_92B161,
    "tab.selectedBorder": C.HEX_92B161,
    "tab.selectedBackground": C.HEX_2E4012,
    "tab.selectedForeground": C.HEX_92B161,
    "tab.unfocusedActiveBorderTop": C.HEX_61704A,
    "tab.lastPinnedBorder": C.HEX_1A2D00,
    "tab.unfocusedInactiveBackground": C.HEX_0D1303,
    "tab.unfocusedInactiveForeground": C.HEX_61704A,
    "tab.unfocusedHoverBackground": C.HEX_172304,
    "tab.unfocusedHoverForeground": C.HEX_61704A,
    "tab.hoverBorder": C.HEX_92B161,
    "tab.unfocusedHoverBorder": C.HEX_61704A,
    "tab.activeModifiedBorder": C.HEX_E6DB74,
    "tab.inactiveModifiedBorder": C.HEX_61704A,
    "tab.unfocusedActiveModifiedBorder": C.HEX_E6DB74,
    "tab.unfocusedInactiveModifiedBorder": C.HEX_61704A,
    "editorPane.background": C.HEX_0D1303,
    "sideBySideEditor.horizontalBorder": C.HEX_1A2D00,
    "sideBySideEditor.verticalBorder": C.HEX_1A2D00,
    "diffEditor.insertedTextBackground": C.HEX_2E4012,
    "diffEditor.insertedTextBorder": C.HEX_A6E22E,
    "diffEditor.removedTextBackground": C.HEX_2E4012,
    "diffEditor.removedTextBorder": C.HEX_F92672,
    "diffEditor.border": C.HEX_1A2D00,
    "diffEditor.diagonalFill": C.HEX_2E4012,
    "diffEditor.insertedLineBackground": C.HEX_2E4012,
    "diffEditor.removedLineBackground": C.HEX_2E4012,
    "diffEditorGutter.insertedLineBackground": C.HEX_A6E22E,
    "diffEditorGutter.removedLineBackground": C.HEX_F92672,
    "diffEditorOverview.insertedForeground": C.HEX_A6E22E,
    "diffEditorOverview.removedForeground": C.HEX_F92672,
    "diffEditor.unchangedRegionBackground": C.HEX_172304,
    "diffEditor.unchangedRegionForeground": C.HEX_61704A,
    "diffEditor.unchangedRegionShadow": C.HEX_414339,
    "diffEditor.unchangedCodeBackground": C.HEX_0D1303,
    "diffEditor.move.border": C.HEX_E6DB74,
    "diffEditor.moveActive.border": C.HEX_F92672,
    "multiDiffEditor.headerBackground": C.HEX_172304,
    "multiDiffEditor.background": C.HEX_0D1303,
    "multiDiffEditor.border": C.HEX_1A2D00,
    "chat.background": C.HEX_172304,
    "chat.foreground": C.HEX_92B161,
    "chat.border": C.HEX_1A2D00,
    "chat.requestBackground": C.HEX_172304,
    "chat.requestForeground": C.HEX_92B161,
    "chat.requestBorder": C.HEX_1A2D00,
    "chat.requestBubbleBackground": C.HEX_172304,
    "chat.requestBubbleBorder": C.HEX_2E4012,
    "chat.responseBackground": C.HEX_1A2D00,
    "chat.responseForeground": C.HEX_92B161,
    "chat.responseBorder": C.HEX_1A2D00,
    "chat.responseBubbleBackground": C.HEX_1A2D00,
    "chat.responseBubbleBorder": C.HEX_2E4012,
    "chat.slashCommandBackground": C.HEX_2E4012,
    "chat.slashCommandForeground": C.HEX_92B161,
    "chat.slashCommandBorder": C.HEX_3A5412,
    "chat.avatarBackground": C.HEX_F92672,
    "chat.avatarForeground": C.HEX_FFFFFF,
    "chat.editedFileForeground": C.HEX_92B161,
    "chat.requestCodeBorder": C.HEX_3A5412,
    "chat.responseCodeBorder": C.HEX_3A5412,
    "chat.codeBlockBackground": C.HEX_172304,
    "chat.codeBlockBorder": C.HEX_2E4012,
    "chat.highlightBackground": C.HEX_3A5412,
    "chat.highlightForeground": C.HEX_92B161,
    "chat.errorBackground": C.HEX_F9267220,
    "chat.errorForeground": C.HEX_F92672,
    "chat.warningBackground": C.HEX_E6DB7420,
    "chat.warningForeground": C.HEX_E6DB74,
    "chat.infoBackground": C.HEX_819AFF20,
    "chat.infoForeground": C.HEX_819AFF,
    "chat.inputBackground": C.HEX_0D1303,
    "chat.inputForeground": C.HEX_92B161,
    "chat.inputBorder": C.HEX_1A2D00,
    "chat.inputPlaceholderForeground": C.HEX_61704A,
    "inlineChat.background": C.HEX_172304,
    "inlineChat.foreground": C.HEX_92B161,
    "inlineChat.border": C.HEX_1A2D00,
    "inlineChat.shadow": C.HEX_0D1303,
    "inlineChatInput.border": C.HEX_1A2D00,
    "inlineChatInput.focusBorder": C.HEX_92B161,
    "inlineChatInput.placeholderForeground": C.HEX_3A5412,
    "inlineChatInput.background": C.HEX_0D1303,
    "inlineChatDiff.inserted": C.HEX_2E4012,
    "inlineChatDiff.removed": C.HEX_2E4012,
    "interactive.background": C.HEX_172304,
    "interactive.foreground": C.HEX_92B161,
    "interactive.border": C.HEX_1A2D00,
    "interactive.activeCodeBorder": C.HEX_92B161,
    "interactive.inactiveCodeBorder": C.HEX_61704A,
    "interactive.codeBackground": C.HEX_172304,
    "interactive.codeForeground": C.HEX_92B161,
    "interactive.hoverBackground": C.HEX_2E4012,
    "interactive.selectedBackground": C.HEX_3A5412,
    "editorWidget.foreground": C.HEX_92B161,
    "editorWidget.background": C.HEX_172304,
    "editorWidget.border": C.HEX_1A2D00,
    "editorWidget.resizeBorder": C.HEX_92B161,
    "editorSuggestWidget.background": C.HEX_172304,
    "editorSuggestWidget.border": C.HEX_1A2D00,
    "editorSuggestWidget.foreground": C.HEX_92B161,
    "editorSuggestWidget.focusHighlightForeground": C.HEX_F92672,
    "editorSuggestWidget.highlightForeground": C.HEX_F92672,
    "editorSuggestWidget.selectedBackground": C.HEX_3A5412,
    "editorSuggestWidget.selectedForeground": C.HEX_92B161,
    "editorSuggestWidget.selectedIconForeground": C.HEX_F92672,
    "editorSuggestWidgetStatus.foreground": C.HEX_61704A,
    "editorHoverWidget.foreground": C.HEX_92B161,
    "editorHoverWidget.background": C.HEX_172304,
    "editorHoverWidget.border": C.HEX_1A2D00,
    "editorHoverWidget.highlightForeground": C.HEX_F92672,
    "editorHoverWidget.statusBarBackground": C.HEX_0D1303,
    "editorGhostText.border": C.HEX_61704A,
    "editorGhostText.background": C.HEX_2E4012,
    "editorGhostText.foreground": C.HEX_61704A,
    "editorStickyScroll.background": C.HEX_172304,
    "editorStickyScroll.border": C.HEX_1A2D00,
    "editorStickyScroll.shadow": C.HEX_0D1303,
    "editorStickyScrollHover.background": C.HEX_2E4012,
    "debugExceptionWidget.background": C.HEX_172304,
    "debugExceptionWidget.border": C.HEX_F92672,
    "editorMarkerNavigation.background": C.HEX_172304,
    "editorMarkerNavigationError.background": C.HEX_F92672,
    "editorMarkerNavigationWarning.background": C.HEX_E6DB74,
    "editorMarkerNavigationInfo.background": C.HEX_819AFF,
    "editorMarkerNavigationError.headerBackground": C.HEX_2E4012,
    "editorMarkerNavigationWarning.headerBackground": C.HEX_2E4012,
    "editorMarkerNavigationInfo.headerBackground": C.HEX_2E4012,
    "peekView.border": C.HEX_92B161,
    "peekViewEditor.background": C.HEX_172304,
    "peekViewEditorGutter.background": C.HEX_0D1303,
    "peekViewEditor.matchHighlightBackground": C.HEX_3A5412,
    "peekViewEditor.matchHighlightBorder": C.HEX_F92672,
    "peekViewResult.background": C.HEX_172304,
    "peekViewResult.fileForeground": C.HEX_92B161,
    "peekViewResult.lineForeground": C.HEX_61704A,
    "peekViewResult.matchHighlightBackground": C.HEX_3A5412,
    "peekViewResult.selectionBackground": C.HEX_3A5412,
    "peekViewResult.selectionForeground": C.HEX_92B161,
    "peekViewTitle.background": C.HEX_0D1303,
    "peekViewTitleDescription.foreground": C.HEX_61704A,
    "peekViewTitleLabel.foreground": C.HEX_92B161,
    "peekViewEditorStickyScroll.background": C.HEX_172304,
    "merge.currentHeaderBackground": C.HEX_2E4012,
    "merge.currentContentBackground": C.HEX_2E4012,
    "merge.incomingHeaderBackground": C.HEX_2E4012,
    "merge.incomingContentBackground": C.HEX_2E4012,
    "merge.border": C.HEX_92B161,
    "merge.commonContentBackground": C.HEX_172304,
    "merge.commonHeaderBackground": C.HEX_172304,
    "editorOverviewRuler.currentContentForeground": C.HEX_92B161,
    "editorOverviewRuler.incomingContentForeground": C.HEX_F92672,
    "editorOverviewRuler.commonContentForeground": C.HEX_61704A,
    "editorOverviewRuler.commentForeground": C.HEX_57702F,
    "editorOverviewRuler.commentUnresolvedForeground": C.HEX_F92672,
    "mergeEditor.change.background": C.HEX_2E4012,
    "mergeEditor.change.word.background": C.HEX_3A5412,
    "mergeEditor.conflict.unhandledUnfocused.border": C.HEX_61704A,
    "mergeEditor.conflict.unhandledFocused.border": C.HEX_F92672,
    "mergeEditor.conflict.handledUnfocused.border": C.HEX_61704A,
    "mergeEditor.conflict.handledFocused.border": C.HEX_92B161,
    "mergeEditor.conflict.handled.minimapOverViewRuler": C.HEX_92B161,
    "mergeEditor.conflict.unhandled.minimapOverViewRuler": C.HEX_F92672,
    "mergeEditor.conflictingLines.background": C.HEX_2E4012,
    "mergeEditor.changeBase.background": C.HEX_172304,
    "mergeEditor.changeBase.word.background": C.HEX_2E4012,
    "mergeEditor.conflict.input1.background": C.HEX_2E4012,
    "mergeEditor.conflict.input2.background": C.HEX_3A5412,
    "panel.dropBorder": C.HEX_92B161,
    "panelTitle.border": C.HEX_1A2D00,
    "panelTitleBadge.background": C.HEX_F92672,
    "panelTitleBadge.foreground": C.HEX_FFFFFF,
    "panelInput.border": C.HEX_1A2D00,
    "panelSection.border": C.HEX_1A2D00,
    "panelSection.dropBackground": C.HEX_3A5412,
    "panelSectionHeader.background": C.HEX_172304,
    "panelSectionHeader.foreground": C.HEX_92B161,
    "panelStickyScroll.background": C.HEX_172304,
    "panelStickyScroll.border": C.HEX_1A2D00,
    "panelStickyScroll.shadow": C.HEX_0D1303,
    "outputView.background": C.HEX_0D1303,
    "outputViewStickyScroll.background": C.HEX_172304,
    "statusBar.debuggingBorder": C.HEX_AE81FF,
    "statusBar.noFolderForeground": C.HEX_92B161,
    "statusBar.noFolderBorder": C.HEX_1A2D00,
    "statusBarItem.activeBackground": C.HEX_3A5412,
    "statusBarItem.hoverForeground": C.HEX_92B161,
    "statusBarItem.hoverBackground": C.HEX_2E4012,
    "statusBarItem.prominentForeground": C.HEX_FFFFFF,
    "statusBarItem.prominentBackground": C.HEX_F92672,
    "statusBarItem.prominentHoverForeground": C.HEX_FFFFFF,
    "statusBarItem.prominentHoverBackground": C.HEX_E6DB74,
    "statusBarItem.remoteHoverBackground": C.HEX_2E4012,
    "statusBarItem.remoteHoverForeground": C.HEX_92B161,
    "statusBarItem.errorBackground": C.HEX_F92672,
    "statusBarItem.errorForeground": C.HEX_FFFFFF,
    "statusBarItem.errorHoverBackground": C.HEX_E6DB74,
    "statusBarItem.errorHoverForeground": C.HEX_172304,
    "statusBarItem.warningBackground": C.HEX_E6DB74,
    "statusBarItem.warningForeground": C.HEX_172304,
    "statusBarItem.warningHoverBackground": C.HEX_F92672,
    "statusBarItem.warningHoverForeground": C.HEX_FFFFFF,
    "statusBarItem.compactHoverBackground": C.HEX_2E4012,
    "statusBarItem.focusBorder": C.HEX_92B161,
    "statusBar.focusBorder": C.HEX_92B161,
    "statusBarItem.offlineBackground": C.HEX_61704A,
    "statusBarItem.offlineForeground": C.HEX_92B161,
    "statusBarItem.offlineHoverForeground": C.HEX_92B161,
    "statusBarItem.offlineHoverBackground": C.HEX_2E4012,
    "titleBar.border": C.HEX_1A2D00,
    "menubar.selectionForeground": C.HEX_92B161,
    "menubar.selectionBackground": C.HEX_3A5412,
    "menubar.selectionBorder": C.HEX_92B161,
    "menu.selectionBorder": C.HEX_92B161,
    "menu.border": C.HEX_1A2D00,
    "commandCenter.foreground": C.HEX_92B161,
    "commandCenter.activeForeground": C.HEX_F92672,
    "commandCenter.background": C.HEX_0D1303,
    "commandCenter.activeBackground": C.HEX_172304,
    "commandCenter.border": C.HEX_0D1303,
    "commandCenter.inactiveForeground": C.HEX_3A5412,
    "commandCenter.inactiveBorder": C.HEX_172304,
    "commandCenter.activeBorder": C.HEX_92B161,
    "commandCenter.debuggingBackground": C.HEX_AE81FF,
    "notificationCenter.border": C.HEX_1A2D00,
    "notificationCenterHeader.foreground": C.HEX_92B161,
    "notificationCenterHeader.background": C.HEX_172304,
    "notificationToast.border": C.HEX_1A2D00,
    "notifications.foreground": C.HEX_92B161,
    "notifications.background": C.HEX_172304,
    "notifications.border": C.HEX_1A2D00,
    "notificationLink.foreground": C.HEX_F92672,
    "notificationsErrorIcon.foreground": C.HEX_F92672,
    "notificationsWarningIcon.foreground": C.HEX_E6DB74,
    "notificationsInfoIcon.foreground": C.HEX_819AFF,
    "banner.background": C.HEX_172304,
    "banner.foreground": C.HEX_92B161,
    "banner.iconForeground": C.HEX_F92672,
    "extensionButton.prominentForeground": C.HEX_FFFFFF,
    "extensionButton.prominentBackground": C.HEX_F92672,
    "extensionButton.prominentHoverBackground": C.HEX_E6DB74,
    "extensionButton.background": C.HEX_3A5412,
    "extensionButton.foreground": C.HEX_92B161,
    "extensionButton.hoverBackground": C.HEX_4A6B1A,
    "extensionButton.separator": C.HEX_2E4012,
    "extensionBadge.remoteBackground": C.HEX_F92672,
    "extensionBadge.remoteForeground": C.HEX_FFFFFF,
    "extensionIcon.starForeground": C.HEX_E6DB74,
    "extensionIcon.verifiedForeground": C.HEX_A6E22E,
    "extensionIcon.preReleaseForeground": C.HEX_AE81FF,
    "extensionIcon.sponsorForeground": C.HEX_F92672,
    "extensionIcon.privateForeground": C.HEX_61704A,
    "pickerGroup.border": C.HEX_1A2D00,
    "pickerGroup.foreground": C.HEX_92B161,
    "quickInputTitle.background": C.HEX_0D1303,
    "keybindingLabel.background": C.HEX_3A5412,
    "keybindingLabel.foreground": C.HEX_92B161,
    "keybindingLabel.border": C.HEX_61704A,
    "keybindingLabel.bottomBorder": C.HEX_92B161,
    "keybindingTable.headerBackground": C.HEX_172304,
    "keybindingTable.rowsBackground": C.HEX_0D1303,
    "terminal.border": C.HEX_1A2D00,
    "terminal.selectionBackground": C.HEX_3A5412,
    "terminal.selectionForeground": C.HEX_FFFFFF,
    "terminal.inactiveSelectionBackground": C.HEX_2E4012,
    "terminal.findMatchBackground": C.HEX_3A5412,
    "terminal.findMatchBorder": C.HEX_F92672,
    "terminal.findMatchHighlightBackground": C.HEX_2E4012,
    "terminal.findMatchHighlightBorder": C.HEX_E6DB74,
    "terminal.hoverHighlightBackground": C.HEX_2E4012,
    "terminalCursor.background": C.HEX_92B161,
    "terminalCursor.foreground": C.HEX_92B161,
    "terminal.dropBackground": C.HEX_2E4012,
    "terminal.tab.activeBorder": C.HEX_92B161,
    "terminalCommandDecoration.defaultBackground": C.HEX_61704A,
    "terminalCommandDecoration.successBackground": C.HEX_A6E22E,
    "terminalCommandDecoration.errorBackground": C.HEX_F92672,
    "terminalOverviewRuler.cursorForeground": C.HEX_92B161,
    "terminalOverviewRuler.findMatchForeground": C.HEX_F92672,
    "terminalStickyScroll.background": C.HEX_172304,
    "terminalStickyScroll.border": C.HEX_1A2D00,
    "terminalStickyScrollHover.background": C.HEX_2E4012,
    "terminal.initialHintForeground": C.HEX_61704A,
    "terminalOverviewRuler.border": C.HEX_1A2D00,
    "terminalCommandGuide.foreground": C.HEX_61704A,
    "terminalSymbolIcon.aliasForeground": C.HEX_FD971F,
    "terminalSymbolIcon.flagForeground": C.HEX_F92672,
    "terminalSymbolIcon.optionForeground": C.HEX_A6E22E,
    "terminalSymbolIcon.optionValueForeground": C.HEX_AE81FF,
    "terminalSymbolIcon.methodForeground": C.HEX_66D9EF,
    "terminalSymbolIcon.argumentForeground": C.HEX_FD971F,
    "terminalSymbolIcon.inlineSuggestionForeground": C.HEX_66D9EF_2,
    "terminalSymbolIcon.fileForeground": C.HEX_92B161,
    "terminalSymbolIcon.folderForeground": C.HEX_A6E22E,
    "debugToolBar.background": C.HEX_172304,
    "debugToolBar.border": C.HEX_1A2D00,
    "editor.stackFrameHighlightBackground": C.HEX_2E4012,
    "editor.focusedStackFrameHighlightBackground": C.HEX_3A5412,
    "editor.inlineValuesForeground": C.HEX_92B161,
    "editor.inlineValuesBackground": C.HEX_2E4012,
    "debugView.exceptionLabelForeground": C.HEX_F92672,
    "debugView.exceptionLabelBackground": C.HEX_2E4012,
    "debugView.stateLabelForeground": C.HEX_92B161,
    "debugView.stateLabelBackground": C.HEX_2E4012,
    "debugView.valueChangedHighlight": C.HEX_E6DB74,
    "debugTokenExpression.name": C.HEX_FD971F,
    "debugTokenExpression.value": C.HEX_92B161,
    "debugTokenExpression.string": C.HEX_E6DB74,
    "debugTokenExpression.boolean": C.HEX_AE81FF,
    "debugTokenExpression.number": C.HEX_AE81FF,
    "debugTokenExpression.error": C.HEX_F92672,
    "debugTokenExpression.type": C.HEX_A6E22E,
    "testing.runAction": C.HEX_A6E22E,
    "testing.iconErrored": C.HEX_F92672,
    "testing.iconFailed": C.HEX_F92672,
    "testing.iconPassed": C.HEX_A6E22E,
    "testing.iconQueued": C.HEX_E6DB74,
    "testing.iconUnset": C.HEX_61704A,
    "testing.iconSkipped": C.HEX_819AFF,
    "testing.iconErrored.retired": C.HEX_61704A,
    "testing.iconFailed.retired": C.HEX_61704A,
    "testing.iconPassed.retired": C.HEX_61704A,
    "testing.iconQueued.retired": C.HEX_61704A,
    "testing.iconUnset.retired": C.HEX_61704A,
    "testing.iconSkipped.retired": C.HEX_61704A,
    "testing.peekBorder": C.HEX_92B161,
    "testing.peekHeaderBackground": C.HEX_172304,
    "testing.message.error.lineBackground": C.HEX_2E4012,
    "testing.message.info.decorationForeground": C.HEX_819AFF,
    "testing.message.info.lineBackground": C.HEX_2E4012,
    "testing.messagePeekBorder": C.HEX_92B161,
    "testing.messagePeekHeaderBackground": C.HEX_172304,
    "testing.coveredBackground": C.HEX_2E4012,
    "testing.coveredBorder": C.HEX_A6E22E,
    "testing.coveredGutterBackground": C.HEX_A6E22E,
    "testing.uncoveredBranchBackground": C.HEX_2E4012,
    "testing.uncoveredBackground": C.HEX_2E4012,
    "testing.uncoveredBorder": C.HEX_F92672,
    "testing.uncoveredGutterBackground": C.HEX_F92672,
    "testing.coverCountBadgeBackground": C.HEX_F92672,
    "testing.coverCountBadgeForeground": C.HEX_FFFFFF,
    "testing.message.error.badgeBackground": C.HEX_F92672,
    "testing.message.error.badgeBorder": C.HEX_F92672,
    "testing.message.error.badgeForeground": C.HEX_FFFFFF,
    "welcomePage.background": C.HEX_0D1303,
    "welcomePage.progress.background": C.HEX_61704A,
    "welcomePage.progress.foreground": C.HEX_92B161,
    "welcomePage.tileBackground": C.HEX_172304,
    "welcomePage.tileHoverBackground": C.HEX_2E4012,
    "welcomePage.tileBorder": C.HEX_1A2D00,
    "walkThrough.embeddedEditorBackground": C.HEX_172304,
    "walkthrough.stepTitle.foreground": C.HEX_92B161,
    "gitDecoration.addedResourceForeground": C.HEX_A6E22E,
    "gitDecoration.modifiedResourceForeground": C.HEX_E6DB74,
    "gitDecoration.deletedResourceForeground": C.HEX_F92672,
    "gitDecoration.renamedResourceForeground": C.HEX_66D9EF,
    "gitDecoration.stageModifiedResourceForeground": C.HEX_A6E22E,
    "gitDecoration.stageDeletedResourceForeground": C.HEX_F92672,
    "gitDecoration.untrackedResourceForeground": C.HEX_819AFF,
    "gitDecoration.ignoredResourceForeground": C.HEX_61704A,
    "gitDecoration.conflictingResourceForeground": C.HEX_FD971F,
    "gitDecoration.submoduleResourceForeground": C.HEX_AE81FF,
    "git.blame.editorDecorationForeground": C.HEX_61704A,
    "scmGraph.historyItemHoverLabelForeground": C.HEX_92B161,
    "scmGraph.foreground1": C.HEX_F92672,
    "scmGraph.foreground2": C.HEX_A6E22E,
    "scmGraph.foreground3": C.HEX_66D9EF,
    "scmGraph.foreground4": C.HEX_E6DB74,
    "scmGraph.foreground5": C.HEX_AE81FF,
    "scmGraph.historyItemHoverAdditionsForeground": C.HEX_A6E22E,
    "scmGraph.historyItemHoverDeletionsForeground": C.HEX_F92672,
    "scmGraph.historyItemRefColor": C.HEX_92B161,
    "scmGraph.historyItemRemoteRefColor": C.HEX_F92672,
    "scmGraph.historyItemBaseRefColor": C.HEX_61704A,
    "scmGraph.historyItemHoverDefaultLabelForeground": C.HEX_92B161,
    "scmGraph.historyItemHoverDefaultLabelBackground": C.HEX_2E4012,
    "settings.headerForeground": C.HEX_92B161,
    "settings.modifiedItemIndicator": C.HEX_E6DB74,
    "settings.dropdownBackground": C.HEX_172304,
    "settings.dropdownForeground": C.HEX_92B161,
    "settings.dropdownBorder": C.HEX_1A2D00,
    "settings.dropdownListBorder": C.HEX_1A2D00,
    "settings.checkboxBackground": C.HEX_172304,
    "settings.checkboxForeground": C.HEX_92B161,
    "settings.checkboxBorder": C.HEX_1A2D00,
    "settings.rowHoverBackground": C.HEX_2E4012,
    "settings.textInputBackground": C.HEX_172304,
    "settings.textInputForeground": C.HEX_92B161,
    "settings.textInputBorder": C.HEX_1A2D00,
    "settings.numberInputBackground": C.HEX_172304,
    "settings.numberInputForeground": C.HEX_92B161,
    "settings.numberInputBorder": C.HEX_1A2D00,
    "settings.focusedRowBackground": C.HEX_2E4012,
    "settings.focusedRowBorder": C.HEX_92B161,
    "settings.headerBorder": C.HEX_1A2D00,
    "settings.sashBorder": C.HEX_1A2D00,
    "settings.settingsHeaderHoverForeground": C.HEX_92B161,
    "breadcrumb.foreground": C.HEX_61704A,
    "breadcrumb.background": C.HEX_172304,
    "breadcrumb.focusForeground": C.HEX_92B161,
    "breadcrumb.activeSelectionForeground": C.HEX_F92672,
    "breadcrumbPicker.background": C.HEX_172304,
    "editor.snippetTabstopHighlightBackground": C.HEX_2E4012,
    "editor.snippetTabstopHighlightBorder": C.HEX_92B161,
    "editor.snippetFinalTabstopHighlightBackground": C.HEX_3A5412,
    "editor.snippetFinalTabstopHighlightBorder": C.HEX_F92672,
    "symbolIcon.arrayForeground": C.HEX_AE81FF,
    "symbolIcon.booleanForeground": C.HEX_AE81FF,
    "symbolIcon.classForeground": C.HEX_A6E22E,
    "symbolIcon.colorForeground": C.HEX_F92672,
    "symbolIcon.constantForeground": C.HEX_AE81FF,
    "symbolIcon.constructorForeground": C.HEX_66D9EF,
    "symbolIcon.enumeratorForeground": C.HEX_AE81FF,
    "symbolIcon.enumeratorMemberForeground": C.HEX_AE81FF,
    "symbolIcon.eventForeground": C.HEX_F92672,
    "symbolIcon.fieldForeground": C.HEX_FD971F,
    "symbolIcon.fileForeground": C.HEX_92B161,
    "symbolIcon.folderForeground": C.HEX_A6E22E,
    "symbolIcon.functionForeground": C.HEX_66D9EF,
    "symbolIcon.interfaceForeground": C.HEX_A6E22E,
    "symbolIcon.keyForeground": C.HEX_FD971F,
    "symbolIcon.keywordForeground": C.HEX_F92672,
    "symbolIcon.methodForeground": C.HEX_66D9EF,
    "symbolIcon.moduleForeground": C.HEX_A6E22E,
    "symbolIcon.namespaceForeground": C.HEX_A6E22E,
    "symbolIcon.nullForeground": C.HEX_AE81FF,
    "symbolIcon.numberForeground": C.HEX_AE81FF,
    "symbolIcon.objectForeground": C.HEX_FD971F,
    "symbolIcon.operatorForeground": C.HEX_F92672,
    "symbolIcon.packageForeground": C.HEX_A6E22E,
    "symbolIcon.propertyForeground": C.HEX_FD971F,
    "symbolIcon.referenceForeground": C.HEX_92B161,
    "symbolIcon.snippetForeground": C.HEX_E6DB74,
    "symbolIcon.stringForeground": C.HEX_E6DB74,
    "symbolIcon.structForeground": C.HEX_A6E22E,
    "symbolIcon.textForeground": C.HEX_92B161,
    "symbolIcon.typeParameterForeground": C.HEX_A6E22E,
    "symbolIcon.unitForeground": C.HEX_AE81FF,
    "symbolIcon.variableForeground": C.HEX_FD971F,
    "debugIcon.breakpointForeground": C.HEX_F92672,
    "debugIcon.breakpointDisabledForeground": C.HEX_61704A,
    "debugIcon.breakpointUnverifiedForeground": C.HEX_E6DB74,
    "debugIcon.breakpointCurrentStackframeForeground": C.HEX_92B161,
    "debugIcon.breakpointStackframeForeground": C.HEX_92B161,
    "debugIcon.startForeground": C.HEX_A6E22E,
    "debugIcon.pauseForeground": C.HEX_E6DB74,
    "debugIcon.stopForeground": C.HEX_F92672,
    "debugIcon.disconnectForeground": C.HEX_F92672,
    "debugIcon.restartForeground": C.HEX_66D9EF,
    "debugIcon.stepOverForeground": C.HEX_92B161,
    "debugIcon.stepIntoForeground": C.HEX_92B161,
    "debugIcon.stepOutForeground": C.HEX_92B161,
    "debugIcon.continueForeground": C.HEX_A6E22E,
    "debugIcon.stepBackForeground": C.HEX_FD971F,
    "debugConsole.infoForeground": C.HEX_819AFF,
    "debugConsole.warningForeground": C.HEX_E6DB74,
    "debugConsole.errorForeground": C.HEX_F92672,
    "debugConsole.sourceForeground": C.HEX_92B161,
    "debugConsoleInputIcon.foreground": C.HEX_61704A,
    "notebook.editorBackground": C.HEX_172304,
    "notebook.cellBorderColor": C.HEX_1A2D00,
    "notebook.cellHoverBackground": C.HEX_2E4012,
    "notebook.cellInsertionIndicator": C.HEX_92B161,
    "notebook.cellStatusBarItemHoverBackground": C.HEX_2E4012,
    "notebook.cellToolbarSeparator": C.HEX_2E4012,
    "notebook.cellEditorBackground": C.HEX_0D1303,
    "notebook.focusedCellBackground": C.HEX_2E4012,
    "notebook.focusedCellBorder": C.HEX_92B161,
    "notebook.focusedEditorBorder": C.HEX_92B161,
    "notebook.inactiveFocusedCellBorder": C.HEX_61704A,
    "notebook.inactiveSelectedCellBorder": C.HEX_61704A,
    "notebook.outputContainerBackgroundColor": C.HEX_0D1303,
    "notebook.outputContainerBorderColor": C.HEX_1A2D00,
    "notebook.selectedCellBackground": C.HEX_2E4012,
    "notebook.selectedCellBorder": C.HEX_61704A,
    "notebook.symbolHighlightBackground": C.HEX_2E4012,
    "notebookScrollbarSlider.activeBackground": C.HEX_5A8A22,
    "notebookScrollbarSlider.background": C.HEX_3A5412,
    "notebookScrollbarSlider.hoverBackground": C.HEX_4A6B1A,
    "notebookStatusErrorIcon.foreground": C.HEX_F92672,
    "notebookStatusRunningIcon.foreground": C.HEX_E6DB74,
    "notebookStatusSuccessIcon.foreground": C.HEX_A6E22E,
    "notebookEditorOverviewRuler.runningCellForeground": C.HEX_E6DB74,
    "charts.foreground": C.HEX_92B161,
    "charts.lines": C.HEX_61704A,
    "charts.red": C.HEX_F92672,
    "charts.blue": C.HEX_819AFF,
    "charts.yellow": C.HEX_E6DB74,
    "charts.orange": C.HEX_FD971F,
    "charts.green": C.HEX_A6E22E,
    "charts.purple": C.HEX_AE81FF,
    "chart.line": C.HEX_92B161,
    "chart.axis": C.HEX_61704A,
    "chart.guide": C.HEX_2E4012,
    "ports.iconRunningProcessForeground": C.HEX_A6E22E,
    "commentsView.resolvedIcon": C.HEX_57702F,
    "commentsView.unresolvedIcon": C.HEX_F92672,
    "actionBar.toggledBackground": C.HEX_3A5412,
    "simpleFindWidget.sashBorder": C.HEX_1A2D00,
    "gauge.background": C.HEX_172304,
    "gauge.foreground": C.HEX_92B161,
    "gauge.border": C.HEX_1A2D00,
    "gauge.warningBackground": C.HEX_E6DB74,
    "gauge.warningForeground": C.HEX_172304,
    "gauge.errorBackground": C.HEX_F92672,
    "gauge.errorForeground": C.HEX_FFFFFF
  },
  "tokenColors": [
    {
      "scope": [
        "comment",
        "punctuation.definition.comment"
      ],
      "settings": {
        "foreground": C.HEX_57702F
      }
    },
    {
      "scope": [
        "comment.documentation"
      ],
      "settings": {
        "foreground": C.HEX_485731
      }
    },
    {
      "scope": [
        "keyword",
        "storage.type",
        "storage.modifier",
        "entity.name.tag"
      ],
      "settings": {
        "foreground": C.HEX_F92672
      }
    },
    {
      "scope": [
        "string",
        "constant.other.symbol",
        "string.quoted",
        "string.template",
        "string.regexp",
        "string.escape",
        "string.special",
        "string.special.symbol",
        "text.literal"
      ],
      "settings": {
        "foreground": C.HEX_E6DB74
      }
    },
    {
      "scope": [
        "variable",
        "variable.parameter",
        "variable.language",
        "variable.other"
      ],
      "settings": {
        "foreground": C.HEX_FD971F
      }
    },
    {
      "scope": [
        "constant.numeric",
        "constant.language.boolean",
        "constant.language"
      ],
      "settings": {
        "foreground": C.HEX_AE81FF,
        "fontStyle": "bold"
      }
    },
    {
      "scope": [
        "entity.name.function",
        "support.function",
        "meta.function-call"
      ],
      "settings": {
        "foreground": C.HEX_66D9EF
      }
    },
    {
      "scope": [
        "entity.name.type",
        "support.type",
        "storage.type"
      ],
      "settings": {
        "foreground": C.HEX_A6E22E_2
      }
    },
    {
      "scope": [
        "constant",
        "constant.character",
        "constant.other"
      ],
      "settings": {
        "foreground": C.HEX_A6E22E
      }
    },
    {
      "scope": [
        "invalid",
        "invalid.deprecated"
      ],
      "settings": {
        "foreground": C.HEX_F92672,
        "fontStyle": "underline"
      }
    },
    {
      "scope": [
        "meta.diff.header",
        "meta.diff.range"
      ],
      "settings": {
        "foreground": C.HEX_A6E22E_2
      }
    },
    {
      "scope": [
        "markup.inserted"
      ],
      "settings": {
        "foreground": C.HEX_A6E22E_2
      }
    },
    {
      "scope": [
        "markup.deleted"
      ],
      "settings": {
        "foreground": C.HEX_F92672
      }
    },
    {
      "scope": [
        "markup.changed"
      ],
      "settings": {
        "foreground": C.HEX_E6DB74
      }
    },
    {
      "scope": [
        "markup.heading",
        "markup.heading entity.name"
      ],
      "settings": {
        "foreground": C.HEX_A6E22E
      }
    },
    {
      "scope": [
        "markup.bold"
      ],
      "settings": {
        "fontStyle": "bold"
      }
    },
    {
      "scope": [
        "markup.italic"
      ],
      "settings": {
        "fontStyle": "italic"
      }
    },
    {
      "scope": [
        "markup.underline"
      ],
      "settings": {
        "fontStyle": "underline"
      }
    },
    {
      "scope": [
        "markup.quote"
      ],
      "settings": {
        "foreground": C.HEX_57702F
      }
    },
    {
      "scope": [
        "markup.list"
      ],
      "settings": {
        "foreground": C.HEX_A6E22E
      }
    },
    {
      "scope": [
        "keyword.control",
        "keyword.operator",
        "keyword.other"
      ],
      "settings": {
        "foreground": C.HEX_F92672
      }
    },
    {
      "scope": [
        "constant.numeric",
        "constant.language",
        "constant.character",
        "constant.other"
      ],
      "settings": {
        "foreground": C.HEX_AE81FF,
        "fontStyle": "bold"
      }
    },
    {
      "scope": [
        "variable",
        "variable.parameter",
        "variable.language",
        "variable.other"
      ],
      "settings": {
        "foreground": C.HEX_FD971F
      }
    },
    {
      "scope": [
        "entity.name.class",
        "entity.name.type.class"
      ],
      "settings": {
        "foreground": C.HEX_A6E22E
      }
    },
    {
      "scope": [
        "entity.name.function",
        "support.function",
        "meta.function-call"
      ],
      "settings": {
        "foreground": C.HEX_66D9EF
      }
    },
    {
      "scope": [
        "entity.name.tag",
        "entity.name.section",
        "entity.name.selector",
        "entity.name.label"
      ],
      "settings": {
        "foreground": C.HEX_F92672
      }
    },
    {
      "scope": [
        "support.class",
        "support.type",
        "support.function",
        "support.constant",
        "support.variable"
      ],
      "settings": {
        "foreground": C.HEX_A6E22E
      }
    },
    {
      "scope": [
        "storage",
        "storage.type",
        "storage.modifier"
      ],
      "settings": {
        "foreground": C.HEX_F92672
      }
    },
    {
      "scope": [
        "punctuation.definition",
        "punctuation.separator",
        "punctuation.terminator"
      ],
      "settings": {
        "foreground": C.HEX_92B161
      }
    },
    {
      "scope": [
        "meta.function",
        "meta.class",
        "meta.block",
        "meta.tag",
        "meta.selector",
        "meta.embedded"
      ],
      "settings": {
        "foreground": C.HEX_92B161
      }
    },
    {
      "scope": [
        "markup.strikethrough"
      ],
      "settings": {
        "fontStyle": "strikethrough"
      }
    },
    {
      "scope": [
        "invalid",
        "invalid.deprecated"
      ],
      "settings": {
        "foreground": C.HEX_F92672,
        "fontStyle": "underline"
      }
    },
    {
      "scope": [
        "comment",
        "comment.line",
        "comment.block",
        "comment.documentation"
      ],
      "settings": {
        "foreground": C.HEX_57702F
      }
    },
    {
      "scope": [
        "string",
        "string.quoted",
        "string.interpolated",
        "string.regexp",
        "string.other"
      ],
      "settings": {
        "foreground": C.HEX_E6DB74
      }
    },
    {
      "scope": [
        "source",
        "text",
        "text.literal"
      ],
      "settings": {
        "foreground": C.HEX_92B161
      }
    }
  ],
  "semanticTokenColors": {
    "namespace": C.HEX_A6E22E,
    "type": C.HEX_A6E22E,
    "class": C.HEX_A6E22E,
    "enum": C.HEX_AE81FF,
    "interface": C.HEX_A6E22E,
    "struct": C.HEX_A6E22E,
    "typeParameter": C.HEX_A6E22E,
    "parameter": C.HEX_FD971F,
    "variable": C.HEX_FD971F,
    "property": C.HEX_FD971F,
    "enumMember": C.HEX_AE81FF,
    "event": C.HEX_F92672,
    "function": C.HEX_66D9EF,
    "method": C.HEX_66D9EF,
    "macro": C.HEX_F92672,
    "keyword": C.HEX_F92672,
    "modifier": C.HEX_F92672,
    "comment": C.HEX_57702F,
    "string": C.HEX_E6DB74,
    "number": C.HEX_AE81FF,
    "regexp": C.HEX_E6DB74,
    "operator": C.HEX_F92672,
    "decorator": C.HEX_F92672,
    "declaration": {
      "fontStyle": "bold"
    },
    "readonly": {
      "fontStyle": "italic"
    },
    "static": {
      "fontStyle": "underline"
    },
    "deprecated": {
      "fontStyle": "strikethrough"
    },
    "abstract": {
      "fontStyle": "italic"
    },
    "async": {
      "fontStyle": "italic"
    },
    "modification": {
      "fontStyle": "underline"
    },
    "documentation": {
      "fontStyle": "italic"
    },
    "defaultLibrary": {
      "fontStyle": "bold"
    }
  }
};
